### ISSUE TITLE
ReactiveCocoa dependency

### ISSUE THREAD

**Issue by Pitometsu** [xareelee/XLReactiveCocoaExtensions#1]
Would you switch to more modern `ReactiveObjc` like it `Overcoat` did, for example https://github.com/Overcoat/Overcoat/pull/152.

**Comment by xareelee** [comment]
@Pitometsu sure, but it takes time. I'm currently using JavaScript/RxJS more than ObjC/Swift due to ReactNative.

**Comment by xareelee** [comment]
I've updated this library to 3.x to switch to ReactiveObjC but with only a little testing. I may not spend more time on this library. If you found any issue or want to contribute, any pull request is welcome.
